### ISSUE TITLE
Missing XCode 8  / iOS 10 Support

### ISSUE THREAD

**Issue by screenworker** [work4blue/sketch-app-asset-export#1]
Hi!

some new Image Sizes in XCode 8 (iOS 10) are currently not supported. See attached Image!
Maybe you have time to fix that.
Thank You

![bildschirmfoto 2016-10-21 um 21 46 14](https://cloud.githubusercontent.com/assets/324108/19609502/e5588490-97d7-11e6-8085-1e4b3f7637c6.png)

**Comment by work4blue** [comment]
buddy,I have fixed that.

**Comment by screenworker** [comment]
Great Job!

Thank you.
