### ISSUE TITLE
Missing macOS Sierra / Sketch42 Export Empty

### ISSUE THREAD

**Issue by shicang1990** [work4blue/sketch-app-asset-export#2]
macOS Sierra: 10.12.3 (16D32)
Sketch42: (36781)

Export empty like this:
![empty](https://cloud.githubusercontent.com/assets/14182785/22726595/38d8dd08-ee0f-11e6-8505-cdb1af3abd57.png)

Sketch like this:
![sketch](https://cloud.githubusercontent.com/assets/14182785/22726554/fc8c39b2-ee0e-11e6-88c0-093f1a0100a3.png)

Maybe you have time to fix that.
Thank You.

**Comment by work4blue** [comment]
fixed can't export image in Sketch 42/41.
please add a star,
enjoy it!

**Comment by shicang1990** [comment]
thank you very much🙂🙂🙂
